version: '3.8'
services:
  izumu-clientes-ui:
    image: izumu-clientes-ui
    ports:
      - "8080:8080"
    networks:
      - izumu-net
    volumes:
      - ./appsettings.override.json:/app/appsettings.json
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

networks:
  izumu-net:
    driver: bridge

